# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

dist: trusty
language: rust
services: docker
sudo: required

# TODO This is the Rust channel that build jobs will use by default but can be
# overridden on a case by case basis down below
rust: nightly-2018-05-07
osx_image: xcode8.2

env:
  global:
    # default job
    - TARGET=x86_64-unknown-linux-gnu

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    # Linux
    # - env: TARGET=x86_64-unknown-linux-gnu  # this is the default job

    # OSX
    #- env: TARGET=x86_64-apple-darwin DISABLE_TESTS=1
    #  os: osx

before_install: set -e

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true
  - cargo install -f rustfmt --vers 0.9.0 || true
  - cargo install -f clippy --vers 0.0.197

script:
  - cargo build --verbose
  - bash ci/script.sh

after_script: set +e

after_success:
  - bash ci/docs.sh

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  except:
    - /design-doc.*/
