# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

dist: trusty
language: rust
services: docker
sudo: required

# TODO This is the Rust channel that build jobs will use by default but can be
# overridden on a case by case basis down below
rust: nightly-2017-01-08

env:
  global:
    # default job
    - TARGET=x86_64-unknown-linux-gnu

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    # Linux
    # - env: TARGET=x86_64-unknown-linux-gnu  # this is the default job

    # OSX
    - env: TARGET=x86_64-apple-darwin DISABLE_TESTS=1
      os: osx

before_install: set -e

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true
  - cargo install rustfmt || true

script:
  - bash ci/script.sh

after_script: set +e

after_success:
  - bash ci/docs.sh

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: ZfqTsdaB6xE7j57huV2UwQI1ibEBPrGvPw5e3sHTEldMFL8sIPzhvseUVwxmv/4hrrPsDnCt2TUoycEIxg/FGMV/DMEPhAfm/D71Mt83cTMBP9xAAlsyEbbm/cXCIFbLCZ9SJa+PeDuqOtkw4gHp5kAXvi20y5afyyEFiVVzykQEAwVLCSYFeBrs8Q1tyhCiLwCuKpf/GOcR2ANe899kglwIOtIE5cq84DZ5iTCuQ7dizT1e/Xvbfpe0kPZv05abOObJop3etKAvCLlrrQCikBTkZRSSfiyaJw5rc/oRd+9X1vjmq07pRzz30pUTiwkKeAAwj+XKJI2LmGLluGJkgQ5YQhphV5JRzEYNEm1aUj4yg1zrrSHfsYs3iNBZwf5kc0HqZSZLLExDNwrbWU2gjyhVj6vi6jD7KX+gGSrC64Nl4W5rqb4Y4KMjIRlrVef/9TJYNGo1dyun2Hd/knzalZNVfKQNjtNRRFrePufg+0QbKxQGI4oI21//wBK0EJyZ75SvmYkjzO7eT+UoNWo7zHiw+1WWd25B/oRaS0m4Z6e1My75vwNX4uz2IGww1gkJP3GwKH1Z8kSeqXUEQj+NtryOh1RkxKdxsVjn2H96XAzUKdugvl8HCu8i1cSkN+8sAGFmg3cht04vbYTMz/UAOV94fAzf0FVHd8GcvgiMjxw=
  file_glob: true
  file: citybound*
  on:
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

#branches:
#  only:
    # release tags
#    - /^v\d+\.\d+\.\d+.*$/
#    - master