[package]
name = "citybound"
version = "0.1.2"
authors = ["Anselm Eickhoff <anselm.eickhoff@gmail.com>"]
license = "AGPL-3.0"
build = "./game/build.rs"

[[bin]]
name = "citybound"
path = "./game/main.rs"

[workspace]
members = [
    "./engine/allocators",
    "./engine/chunked",
    "./engine/compact",
    "./engine/compact_macros",
    "./engine/descartes",
    "./engine/kay",
    "./engine/kay_macros",
    "./engine/kay_codegen",
    "./engine/monet",
    './engine/stagemaster'
]

[dependencies]
ordered-float = "0.2.3"
itertools = "0.5.5"
clippy = { version = "0.0.157", optional = true }
random = "0.12.2"
fnv = "1.0.3"
roaring = "0.4.0"
open = "1.1.1"
serde = "1.0"
serde_derive = "1.0"
imgui = "0.0.15"
pulldown-cmark = "0.0.14"

[dependencies.compact]
path = "./engine/compact/"

[dependencies.compact_macros]
path = "./engine/compact_macros/"

[dependencies.kay]
path = "./engine/kay/"

[dependencies.kay_macros]
path = "./engine/kay_macros/"

[dependencies.descartes]
path = "./engine/descartes/"

[dependencies.monet]
path = "./engine/monet/"

[dependencies.stagemaster]
path = "./engine/stagemaster/"

[build-dependencies]
kay_codegen = {path = "./engine/kay_codegen/"}

[profile.dev]
opt-level = 1
codegen-units = 4

[profile.release]
debug = true
codegen-units = 4

[features]
default = ["enable-clippy"]

enable-clippy = [
	"clippy",
	"compact/enable-clippy",
	"kay/enable-clippy",
	"descartes/clippy",
	"monet/enable-clippy",
	"stagemaster/enable-clippy"
]

