[package]
name = "compact_macros"
version = "0.1.0"
authors = ["Anselm Eickhoff <anselm.eickhoff@gmail.com>"]

[dependencies]
syn = "=0.10.6"
quote = "0.3"

[dev-dependencies]
pretty_assertions = "0.2.1"

[lib]
proc-macro = true