[package]
name = "chunked"
version = "0.1.0"
authors = ["Anselm Eickhoff <anselm.eickhoff@gmail.com>"]

[dependencies]
clippy = { version = "0.0.157", optional = true }

[dependencies.allocators]
path = "../allocators/"

[features]
enable-clippy = [
	"clippy"
	, "allocators/clippy"
]

